com.github.srang.madness:
  debug: ${APP_DEBUG:true}
  region.size: 16

"%dev":
  quarkus:
    datasource:
      db-kind: h2
      username: test
      password: test
      jdbc:
        url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    hibernate-orm:
      sql-load-script: import.sql
      log.sql: true
      database:
        generation: none



"%openshift":
  quarkus:
    datasource:
      db-kind: pg



#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: ${DB_URL:jdbc:mysql://localhost:3306/madness}
#    username: ${DB_USER:madness}
#    password: ${DB_PASS:tourney}
#    tomcat.max-active: 50
#  messages:
#    basename: locale/messages
#  thymeleaf.cache: false
#  jpa:
#    show-sql: true
#    properties.hibernate.format_sql: true
#
#hibernate:
#  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  show_sql: false
#entitymanager.packages.to.scan: org.srang.madness.manager
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:identity.p12
#    key-store-password: genfare
#    key-store-type: PKCS12
#    key-alias: tomcat